version: '3.3'

volumes:
  mongodb_restaurant:
  db_data:
  redis_data:

services:
  redis:
    restart: always
    image: bitnami/redis:6.0-debian-10
    volumes:
      - redis_data:/bitnami/redis/data
    ports:
      - 44002:6379
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
  mongo:
    restart: always
    image: bitnami/mongodb:4.0
    env_file:
      - ./.env.dev
    volumes:
      - mongodb_restaurant:/bitnami
      - ./mongodump:/dump
    ports:
      - 44000:27017
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
  server:
    build:
      dockerfile: ./server/Dockerfile.dev
      context: ./
    volumes:
      - ./tsconfig.json:/app/tsconfig.json
      - ./node_modules:/app/node_modules
      - ./server:/app/server
    ports:
      - 44001:80
    restart: always
    command: /app/node_modules/.bin/ts-node-dev --poll --transpile-only /app/server/index.ts
    # command: tail -f /dev/null
    env_file:
      - ./.env.dev
  postgres:
    image: postgres:12
    ports:
    - "5432:5432"
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    - ./pgdump:/dump
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v1.2.2
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
